{% set name = "azure-data-tables" %}
{% set version = "12.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-data-tables-{{ version }}.tar.gz
  sha256: 1d68c8401598994e37a52c4a2dcc31e39104c67d748de124c98f47a5bca7d2fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - azure-core <2.0.0,>=1.24.0
    - yarl >=1.0,<2.0
    - isodate >=0.6.0
    - typing-extensions >=4.3.0

test:
  imports:
    - azure.data.tables
    - azure.data.tables._generated
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/table/azure-table
  summary: Microsoft Azure Azure Data Tables Client Library for Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
    - TomAugspurger
